### ISSUE TITLE
Make exams belong to user_courses

### ISSUE THREAD

**Issue by sncalvo** [franciscoaguirre/career-manager#4]
Currently, exams belong to courses. I cannot remember the original design but I believe that it would make more sense if it belonged to user_courses since the exams directly correlate with the state of the user_course. If the user course was not passed or was exonerated then the exam might not be available. Or if the user just passed its course then the exam would be available.

In fact, I look at this in the way that an exam, in most scenarios, cannot exist if the user_course does not even exist. It is still a delicate subject given that in certain cases, mostly the first subjects in an engineer degree, exams can be taken freely, although this is not the case for most of them, or even in most careers. For this reason the exception should be done the other way around and make the exams belong to user_course. From a database standpoint this seems to make more sense to me.

What is your opinion in this matter?

**Comment by franciscoaguirre** [comment]
Yes, it should be as you say
